/**
 * basic_motion.c — Move a single HX-30HM servo on STM32.
 *
 * Setup in STM32CubeIDE / CubeMX:
 *   - Enable USART2 (or any UART), set baud = 1 000 000, 8N1
 *   - Configure TX/RX pins
 *   - Optionally configure one GPIO output for direction control (RS-485)
 *
 * Wiring:
 *   UART TX → 1 kΩ → Servo DATA line
 *   UART RX             ← Servo DATA line (direct)
 *   GND                 ── Servo GND
 *   11.1 V (3S LiPo)   ── Servo V+
 */

#include "main.h"          /* generated by CubeMX, declares huart2 etc. */
#include "hiwonder_servo_stm32.h"

extern UART_HandleTypeDef huart2;

int main(void)
{
    HAL_Init();
    SystemClock_Config();   /* generated */
    MX_GPIO_Init();         /* generated */
    MX_USART2_UART_Init();  /* generated — baud must be 1 000 000 */

    HW_Bus bus = {
        .huart    = &huart2,
        .dir_port = NULL,   /* no direction-control pin — change if using RS-485 */
        .dir_pin  = 0,
        .timeout  = 10,     /* 10 ms HAL timeout */
    };

    uint8_t servo_id = 1;

    /* Ping the servo */
    if (hw_ping(&bus, servo_id)) {
        /* Online — read full status */
        HW_ServoStatus st;
        hw_full_status(&bus, servo_id, &st);
        /* st.position, st.voltage_mv / 1000.0f V, st.temperature */
    }

    /* Move through several positions at 500 steps/s */
    uint16_t positions[] = {0, 1024, 2048, 3072, 4095};
    for (int i = 0; i < 5; i++) {
        hw_move_to(&bus, servo_id, positions[i], /*time_ms=*/0, /*speed=*/500);
        HAL_Delay(1500);

        uint16_t pos;
        hw_get_position(&bus, servo_id, &pos);
        /* pos now holds the current position */
    }

    while (1) {}
}
